-- ============================================================
--  LUMÉ — база замовлень + заявок (з UTM-мітками)
--  Запустіть один раз: Supabase → SQL Editor → New query → Run
-- ============================================================

create table if not exists public.orders (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now(),
  type         text default 'order',     -- 'order' | 'contact'
  name         text,
  phone        text,
  city         text,                       -- місто доставки (з форми)
  np_branch    text,                       -- відділення Нової Пошти (з форми)
  pay          text,
  items        jsonb default '[]',        -- [{title,size,qty,sum}]
  total        integer default 0,
  status       text default 'new',        -- new | processing | done | canceled
  utm_source   text,
  utm_medium   text,
  utm_campaign text,
  utm_term     text,
  utm_content  text,
  geo_country  text,                       -- країна за IP (Vercel)
  geo_region   text,                       -- регіон за IP
  geo_city     text,                       -- місто за IP
  referrer     text,
  landing_page text
);

create index if not exists orders_created_idx on public.orders (created_at desc);

-- RLS: читати/змінювати/видаляти — лише авторизований адмін.
-- Вставку робить серверна функція через service_role (RLS на неї не діє),
-- тому INSERT-політики для anon НЕ створюємо (захист від спаму).
alter table public.orders enable row level security;

drop policy if exists "auth read orders"   on public.orders;
drop policy if exists "auth update orders" on public.orders;
drop policy if exists "auth delete orders" on public.orders;

create policy "auth read orders"   on public.orders for select to authenticated using (true);
create policy "auth update orders" on public.orders for update to authenticated using (true);
create policy "auth delete orders" on public.orders for delete to authenticated using (true);
