-- ============================================================
--  LUMÉ STORE — налаштування бази даних Supabase
--  Запустіть цей скрипт один раз: Supabase → SQL Editor → New query → Run
-- ============================================================

-- 1) Таблиця товарів -----------------------------------------
create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  title       text    not null,
  sku         text,
  category    text,
  price       integer not null default 0,
  old_price   integer,
  badge       text,                       -- 'new' | 'sale' | 'hit' | null
  sizes       text[]  default '{}',       -- напр. {'XL','2XL','3XL'}
  description text,
  image_url   text,                       -- головне фото (= images[1])
  images      text[]  default '{}',       -- галерея фото (порядок = розміщення)
  in_stock    boolean default true,       -- статус наявності
  sort        integer default 0,          -- порядок показу (менше = вище)
  created_at  timestamptz default now()
);

-- 2) Row Level Security: усі можуть читати, писати — лише авторизовані
alter table public.products enable row level security;

drop policy if exists "public read products"  on public.products;
drop policy if exists "auth insert products"  on public.products;
drop policy if exists "auth update products"  on public.products;
drop policy if exists "auth delete products"  on public.products;

create policy "public read products" on public.products
  for select using (true);
create policy "auth insert products" on public.products
  for insert to authenticated with check (true);
create policy "auth update products" on public.products
  for update to authenticated using (true);
create policy "auth delete products" on public.products
  for delete to authenticated using (true);

-- 3) Сховище для фотографій ----------------------------------
insert into storage.buckets (id, name, public)
values ('product-images','product-images', true)
on conflict (id) do nothing;

drop policy if exists "public read images"  on storage.objects;
drop policy if exists "auth upload images"  on storage.objects;
drop policy if exists "auth update images"  on storage.objects;
drop policy if exists "auth delete images"  on storage.objects;

create policy "public read images" on storage.objects
  for select using (bucket_id = 'product-images');
create policy "auth upload images" on storage.objects
  for insert to authenticated with check (bucket_id = 'product-images');
create policy "auth update images" on storage.objects
  for update to authenticated using (bucket_id = 'product-images');
create policy "auth delete images" on storage.objects
  for delete to authenticated using (bucket_id = 'product-images');

-- 4) Початкові товари (демо — за бажанням можна видалити/змінити в адмінці)
insert into public.products (title, sku, category, price, old_price, badge, sizes, sort) values
  ('Сукня міді «Флоренція»','LM-1001','Сукні',1290,1590,'sale','{XL,2XL,3XL,4XL,5XL}',1),
  ('Лляна сорочка «Бриз»','LM-1002','Верх',890,null,'new','{XL,2XL,3XL,4XL,5XL}',2),
  ('Спідниця плісе «Аврора»','LM-1003','Низ',990,1190,'sale','{XL,2XL,3XL,4XL,5XL}',3),
  ('Шкіряна сумка «Мілано»','LM-1004','Аксесуари',1450,null,'hit','{"Один розмір"}',4),
  ('Трикотажна сукня «Осінь»','LM-1005','Сукні',1150,null,null,'{XL,2XL,3XL,4XL,5XL}',5),
  ('Оверсайз худі «Комфорт»','LM-1006','Верх',1090,1290,'sale','{XL,2XL,3XL,4XL,5XL}',6),
  ('Широкі штани «Палаццо»','LM-1007','Низ',1190,null,'new','{XL,2XL,3XL,4XL,5XL}',7),
  ('Шовкова хустка «Версаль»','LM-1008','Аксесуари',490,690,'sale','{"Один розмір"}',8),
  ('Вечірня сукня «Зоря»','LM-1009','Сукні',1890,null,'hit','{XL,2XL,3XL,4XL,5XL}',9),
  ('Базова футболка «Кліо»','LM-1010','Верх',590,null,null,'{XL,2XL,3XL,4XL,5XL}',10),
  ('Джинси «Скіні»','LM-1011','Низ',1290,1490,'sale','{XL,2XL,3XL,4XL,5XL}',11),
  ('Сонцезахисні окуляри «Ріо»','LM-1012','Аксесуари',790,null,'new','{"Один розмір"}',12);
